//id will be generated by mongo
db.userProfile.insert(
{
userName: "SowHa",
password: "hashcode",
role:"Volunteer",

Profile:{
    firstName: "Sowmya",
    LastName: "Hari",
    PhoneNumber : [{"Home":"+14256786766"}, {"Cell":'1234567888'}],
    Bio : "this is some bio which can be really large",
    email:"",
    weeklyComitted_hours:"20",
    professional_Links:[{"LinkedinProfile": " www.something.com"}],
    personal_Links:[{"facebook":""}],
    //point to be discussed :other links field
    otherLinks:[{gDoc:"googledocs.com"},{dropBox:""}],
    createdDate : new Date(),
    lastModifiedDate: new Date()
},
Badges:[{BadgeName:"2x",noOfTimesEarned:"2",lastUpdatedTime:""}]
}
)



